# config.toml

baseURL = "https://kblazewicz.github.io/hautel/" # <-- THIS IS THE FIX
languageCode = "en-us"
title = "Hautel Karniowice"
theme = "ananke" 

[params]
  logo = "/images/logo.png" # Path to your main logo/header image

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1